services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "consul agent -dev -client=0.0.0.0"
    networks:
      - my_network

  clickhouse:
    image: clickhouse
    container_name: some1-clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8123" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - my_network

  app:
    build: .
    container_name: my-app
    ports:
      - "4000:4000"
    depends_on:
      consul:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    environment:
      CONSUL_HOST: consul
      CLICKHOUSE_HOST: some1-clickhouse-server
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_SERVICE_NAME: clickhouse-service
    networks:
      - my_network
    entrypoint: [ "/bin/sh", "-c", "./app/register_service.sh && uvicorn app.main:app --host 0.0.0.0 --port 4000" ]

networks:
  my_network:
    driver: bridge