version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: some1-clickhouse-server
    networks:
      - my_network

  app:
    build: .
    container_name: my-app
    depends_on:
      - clickhouse
    networks:
      - my_network

networks:
  my_network:
    driver: bridge