version: '3'

services:
  clickhouse:
    image: clickhouse/some1-clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
    networks:
      - app-network

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - clickhouse
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
    networks:
      - app-network

volumes:
  clickhouse_data:

networks:
  app-network:
    driver: bridge